/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pitscript;
import java.io.IOException;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import com.jcraft.jsch.SftpException;



public class App {
    
    public String remoteHost = "10.223.57.2";
public String username = "lvuser";
public String password = "";
static App m_main;
static SocketFactoryWithTimeout m_socketFactory = new pitscript.SocketFactoryWithTimeout().getInstance();
static SftpListFiles m_fileLister = new pitscript.SftpListFiles().getInstance();
    public static void main(String[] args) {
        System.out.println("it started");
        App main = new App();
        m_main = main;
        try {
            main.downloadFile();
        } catch (JSchException | SftpException e ) {
            e.printStackTrace();
        }
    }
    private ChannelSftp setupJsch() throws JSchException {
        JSch jsch = new JSch();
        try {
            m_main.m_socketFactory.createSocket(remoteHost,23);
        } catch (IOException e) {
            e.printStackTrace();
        }
        Session jschSession = jsch.getSession(username, remoteHost);
        jschSession.setPassword(password);
        jschSession.connect();
        return (ChannelSftp) jschSession.openChannel("sftp");
    }
    public void downloadFile() throws JSchException, SftpException{
    ChannelSftp channelSftp = setupJsch();
    channelSftp.connect();
    String remoteFile = "/home/lvuser/logs";
    
 
    String localDir = "C:\\Logs";
    try {
        channelSftp.get(remoteFile + (m_fileLister.getFileName(remoteHost,remoteFile)), localDir);
    } catch (IOException e) {
        System.out.println("It coudnt get the file name or the file.");
        e.printStackTrace();
    }
    System.out.println("it worked :)");
    channelSftp.exit();
    
}
}
    